Added Book entity, Book service and Book repository.
sovisou/Online-Book-store pull request #1
Opened 2024-10-03 16:28 UTC by sovisou

2024-10-03 18:37 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-10-03 18:37 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Book.java
> +@Data
```suggestion
@Getter
@Setter
```

Don't use Data for entities

2024-10-03 18:37 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +@Repository
use Lombok annotation to create constructor

2024-10-03 18:37 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            return books;
```suggestion
        try (Session session = sessionFactory.openSession()) {
            return session.createQuery("FROM Book", Book.class).getResultList();
```

2024-10-03 18:37 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/BookServiceImpl.java
> +@Service
use Lombok annotation to create constructor

2024-10-07 17:32 UTC, okuzan approved these changes

2024-10-07 21:40 UTC, merged