Added Category model
sovisou/Online-Book-store pull request #10
Opened 2024-11-07 14:05 UTC by sovisou

2024-11-07 15:08 UTC, Elena-Bruyako requested changes
see comments

2024-11-07 15:08 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/BookController.java
> +    public List getBooksByCategoryId(Long id) {
```suggestion
    public List<BookDtoWithoutCategoryIds> getBooksByCategoryId(@PathVariable Long id) {
```

2024-11-07 15:08 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/CategoryController.java
> +    public List getAll(Pageable pageable) {
It's better to return Page

2024-11-07 15:08 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-11-07 15:08 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/mapper/CategoryMapper.java
> +
remove empty line

2024-11-08 09:22 UTC, Elena-Bruyako requested changes
just two comments

2024-11-08 09:22 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/BookServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-11-08 09:22 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/CategoryService.java
> +
```suggestion
```

2024-11-08 21:37 UTC, sarakhmen approved these changes

2024-11-12 21:23 UTC, merged