Added Order and OrderItems entity.
sovisou/Online-Book-store pull request #12
Opened 2024-11-23 14:03 UTC by sovisou

2024-11-23 16:38 UTC, Elena-Bruyako requested changes
see comments

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/OrderController.java
> +                                      @RequestBody OrderUpdateDto updateDto) {
```suggestion
                                      @RequestBody @Valid OrderUpdateDto updateDto) {
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/OrderController.java
> +    @PostMapping
add PreAuthorize where is needed

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/order/OrderDto.java
> +
```suggestion
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/order/CreateOrderRequestDto.java
> +
```suggestion
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/order/OrderUpdateDto.java
> +    @NotBlank
```suggestion
    @NotNull
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +        Order savedOrder = orderRepository.save(order);
```suggestion
        orderRepository.save(order);
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +        return orderMapper.toDto(savedOrder);
```suggestion
        return orderMapper.toDto(order);
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +                        + userId));
check if shop cart  `getCartItems().isEmpty()`

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +        Order order = new Order();
divide logic to separate methods

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public List<OrderDto> findAllOrders(Long userId) {
```suggestion
    public List<OrderDto> findAllOrders(Long userId, Pageable pageable) {
```

2024-11-23 16:38 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/UserServiceImpl.java
> +        user = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2024-11-26 07:50 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments. But please fix it before merging;)

2024-11-26 07:50 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/dto/order/CreateOrderRequestDto.java
> +    private String shoppingAddress;
```suggestion
    private String shippingAddress;
```

2024-11-26 07:50 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +            throw new EntityNotFoundException("Shopping cart is empty for user with id: " + userId);
better create another exception. For example OrderProcessingException (it should return status CONFLICT)

2024-11-26 07:50 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/service/impl/OrderServiceImpl.java
> +    public List<OrderDto> findAllOrders(Long userId, Pageable pageable) {
better return Page instead List

2024-11-26 15:03 UTC, merged