Added BookController, BookDto and CreateBookRequestDto classes. Also …
sovisou/Online-Book-store pull request #2
Opened 2024-10-07 22:38 UTC by sovisou

…implemented mappers and Mapstruct. Made some changes in service and repository.

2024-10-08 11:13 UTC, Elena-Bruyako requested changes
see comments

2024-10-08 11:13 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>spring-orm</artifactId>
why do you need this dependency?

2024-10-08 11:13 UTC, Elena-Bruyako commented on pom.xml
> +			<artifactId>commons-dbcp2</artifactId>
why do you need this dependency?

2024-10-08 11:13 UTC, Elena-Bruyako commented on pom.xml
> +			<version>0.2.0</version>
```suggestion
			<version>${lombok.mapstruct.binding.version}</version>
```
add version to properties

2024-10-08 11:13 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/controller/BookController.java
> +@RequestMapping(value = "/books")
```suggestion
@RequestMapping("/books")
```

2024-10-08 11:13 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +        }
add catch block

2024-10-08 11:13 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/repository/impl/BookRepositoryImpl.java
> +            Book book = session.find(Book.class, id);
inline with return

2024-10-09 08:18 UTC, ahoienko approved these changes
Good job!

2024-10-09 16:27 UTC, merged