Added CustomGlobalExceptionHandler class and validation for existing …
sovisou/Online-Book-store pull request #5
Opened 2024-10-13 21:20 UTC by sovisou

…DTO classes.

2024-10-14 11:27 UTC, Elena-Bruyako requested changes
see comments

2024-10-14 11:27 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/BookDto.java
> +    @NotNull
Don't need to validate response

2024-10-14 11:27 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/BookDto.java
>      private boolean isDeleted;
remove isDeleted field

2024-10-14 11:27 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/dto/CreateBookRequestDto.java
> +    @NotNull
It's better to use NotBlank for String

```suggestion
    @NotBlank
```

2024-10-14 11:27 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, headers, status);
```suggestion
        return new ResponseEntity<>(body, headers, HttpStatus.BAD_REQUEST);
```

2024-10-14 11:27 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    }
You can also handle EntityNotFoundException

2024-10-15 06:46 UTC, liliia-ponomarenko requested changes
Let's fix issue with EntityNotFoundException;)

2024-10-15 06:46 UTC, liliia-ponomarenko commented on pom.xml
> +			<groupId>org.hibernate.validator</groupId>
better use `spring-boot-starter-validation`

2024-10-15 06:46 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/dto/CreateBookRequestDto.java
> +    @NotBlank
You also can validate the size for literal

2024-10-15 06:46 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +
```suggestion
```

2024-10-15 06:46 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +                                                            WebRequest request) {
do you use `request` parameter?

2024-10-15 06:46 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    @ExceptionHandler(EntityNotFoundException.class)
Handle your custom EntityNotFoundException

2024-10-15 06:46 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/service/impl/BookServiceImpl.java
> +import jakarta.persistence.EntityNotFoundException;
Use your custom EntityNotFoundException

2024-10-15 13:58 UTC, Elena-Bruyako approved these changes
well done

2024-10-15 21:41 UTC, merged