Implemented password hashing, SecurityFilterChain and roles.
sovisou/Online-Book-store pull request #8
Opened 2024-10-29 20:06 UTC by sovisou

2024-10-30 11:05 UTC, JJJazl requested changes

2024-10-30 11:05 UTC, JJJazl commented on src/main/java/com/onlinebookstore/controller/BookController.java
>      public BookDto createBook(@RequestBody @Valid CreateBookRequestDto bookDto) {
Please, add an appropriate status code for POST method

2024-10-30 11:05 UTC, JJJazl commented on src/main/java/com/onlinebookstore/model/Role.java
> +        ADMIN
Spring Security requires use a prefix ROLE_. You can add this prefix to your enum values or change method `getAuthority()` to return "ROLE_" + roleName.name(), but it's better just change enum values
```suggestion
        ROLE_USER,
        ROLE_ADMIN
```

2024-10-30 11:05 UTC, JJJazl commented on src/main/java/com/onlinebookstore/repository/role/RoleRepository.java
> +public interface RoleRepository extends JpaRepository<User, Long> {
```suggestion
public interface RoleRepository extends JpaRepository<Role, Long> {
```

2024-10-30 11:05 UTC, JJJazl commented on src/main/java/com/onlinebookstore/security/CustomUserDetailsService.java
> +    }
```suggestion
        return userRepository.findByEmail(email)
                .orElseThrow(
                        () -> new UsernameNotFoundException("Can't find user by email: " + email));
    }
```

2024-10-31 08:22 UTC, liliia-ponomarenko requested changes
Good job! Let’s fix one important requirement ;)

2024-10-31 08:22 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/config/SecurityConfig.java
> +                                .requestMatchers("/auth/***", "/swagger-ui/**", "/v3/api-docs/**")
```suggestion
                                .requestMatchers("/auth/**", "/swagger-ui/**", "/v3/api-docs/**")
```

2024-10-31 08:22 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/model/User.java
> +public class User implements UserDetails {
Let’s realize soft-deleted for the user entity and override the isEnabled() method.

2024-10-31 08:22 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                    unique: true
add one empty line at the end of the file  (check other files)

2024-11-01 07:59 UTC, liliia-ponomarenko requested changes

2024-11-01 07:59 UTC, liliia-ponomarenko commented on src/main/java/com/onlinebookstore/model/User.java
> +public class User implements UserDetails {
```suggestion
@SQLDelete(sql = "UPDATE users SET is_deleted = true WHERE id = ?")
@Where(clause = "is_deleted=false")
public class User implements UserDetails {
```
Let’s complete soft-deleted realization ;)

2024-11-01 13:52 UTC, Elena-Bruyako requested changes
see comments

2024-11-01 13:52 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/config/SecurityConfig.java
> +@EnableMethodSecurity
Do you really need both of these annotations?

2024-11-01 13:52 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/model/Role.java
> +@Entity
```suggestion
@Entity
@Getter
@Setter
```

2024-11-01 13:52 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/repository/user/UserRepository.java
> +    Optional<User> findByEmail(String email);
```suggestion
    @EntityGraph(attributePaths = "roles")
    Optional<User> findByEmail(String email);
```

2024-11-01 13:52 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/security/CustomUserDetailsService.java
> +                        () -> new UsernameNotFoundException("Can't find user by email: " + email));
```suggestion
                        () -> new EntityNotFoundException("Can't find user by email: " + email));
```

2024-11-01 13:52 UTC, Elena-Bruyako commented on src/main/java/com/onlinebookstore/service/impl/UserServiceImpl.java
> +        user.setPassword(passwordEncoder.encode(requestDto.getPassword()));
find role user and set it up
```suggestion
        user.setPassword(passwordEncoder.encode(requestDto.getPassword()));
        user.setRoles(Set.of(role));
```

2024-11-01 14:59 UTC, Elena-Bruyako approved these changes
well done

2024-11-01 19:12 UTC, merged